MVC_Proyect1/Models/ErrorViewModel.cs
namespace MVC_Proyect1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Proyect1/Controllers/MVCappController.cs
using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;

namespace MVC_Proyect1.Controllers
{
    public class MVCappController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Zodiaco sz)
        {
            string resultado = "";

            //Application.ViewModel.ViewZodiac viewZodiac = new();

            // Acuario ----------------------------------------------------------------------------

            if (sz.Dia >= 21 && sz.Mes == "1")
            {
                resultado = "Acuario♒";
            }
            else if (sz.Dia <= 18 && sz.Mes == "2")
            {
                resultado = "Acuario♒";
            }

            // Piscis ----------------------------------------------------------------------------
            else if (sz.Dia >= 19 && sz.Mes == "2")
            {
                resultado = "Piscis♓";
            }
            else if (sz.Dia <= 20 && sz.Mes == "3")
            {
                resultado = "Piscis♓";
            }
        
            // Aries ----------------------------------------------------------------------------
            else if (sz.Dia >= 21 && sz.Mes == "3")
            {
                resultado = "Aries♈";
            }
            else if (sz.Dia <= 20 && sz.Mes == "4")
            {
                resultado = "Aries♈";
            }

            // Tauro ----------------------------------------------------------------------------
            else if (sz.Dia >= 21 && sz.Mes == "4")
            {
                resultado = "Tauro♉";
            }
            else if (sz.Dia <= 21 && sz.Mes == "5")
            {
                resultado = "Tauro♉";
            }

            // Geminis ----------------------------------------------------------------------------
            else if (sz.Dia >= 22 && sz.Mes == "5")
            {
                resultado = "Geminis♊";
            }
            else if (sz.Dia <= 21 && sz.Mes == "6")
            {
                resultado = "Geminis♊";
            }

            // Cancer ----------------------------------------------------------------------------
            else if (sz.Dia >= 22 && sz.Mes == "6")
            {
                resultado = "Cancer♋";
            }
            else if (sz.Dia <= 22 && sz.Mes == "7")
            {
                resultado = "Cancer♋";
            }

            // Leo ----------------------------------------------------------------------------
            else if(sz.Dia >= 23 && sz.Mes == "7")
            {
                resultado = "Leo♌";
            }
            else if(sz.Dia <= 23 && sz.Mes == "8")
            {
                resultado = "Leo♌";
            }

            // Virgo ----------------------------------------------------------------------------
            else if(sz.Dia >= 24 && sz.Mes == "8")
            {
                resultado = "Virgo♍";
            }
            else if(sz.Dia <= 23 && sz.Mes == "9")
            {
                resultado = "Virgo♍";
            }

            // Libra ----------------------------------------------------------------------------
            else if(sz.Dia >= 24 && sz.Mes == "9")
            {
                resultado = "Libra♎";
            }
            else if(sz.Dia <= 23 && sz.Mes == "10")
            {
                resultado = "Libra♎";
            }

            // Escorpio ----------------------------------------------------------------------------
            else if(sz.Dia >= 24 && sz.Mes == "10")
            {
                resultado = "Escorpio♏";
            }
            else if(sz.Dia <= 22 && sz.Mes == "11")
            {
                resultado = "Escorpio♏";
            }

            // Sagitario ----------------------------------------------------------------------------
            else if(sz.Dia >= 23 && sz.Mes == "11")
            {
                resultado = "Sagitario♐";
            }
            else if(sz.Dia <= 21 && sz.Mes == "12")
            {
                resultado = "Sagitario♐";
            }

            // Capricornio ----------------------------------------------------------------------------
            else if(sz.Dia >= 22 && sz.Mes == "12")
            {
                resultado = "Capricornio♑";
            }
            else if(sz.Dia <= 21 && sz.Mes == "1")
            {
                resultado = "Capricornio♑";
            }

            else
            {
                return BadRequest();
            }
            return RedirectToAction("ZodiacoVista", new { resultado = resultado });
        }

        public IActionResult ZodiacoVista(string resultado) 
        {
            ViewBag.RESULTADO = resultado;
            return View();
        }

        public IActionResult Convertidor()
        {
            return View();
        }

       [HttpPost]
        public IActionResult Convertidor(ConversionVM cs) 
        {
            double Conversion = 0;
        
            if (cs.Tipomoneda == "1")
            {
                Conversion = cs.Entrada / 53.26;
            }

            else if (cs.Tipomoneda == "2")
            {
                Conversion = (cs.Entrada) * 53.26;
            }

            else if (cs.Tipomoneda == "3")
            {
                Conversion = (cs.Entrada) * 0.999624;
            }

            else if (cs.Tipomoneda == "4")
            {
                Conversion = (cs.Entrada) / 0.999624;
            }

            else if (cs.Tipomoneda == "5")
            {
                Conversion = (cs.Entrada) / 53.62;
            }

            else if (cs.Tipomoneda == "6")
            {
                Conversion = (cs.Entrada) * 53.62;
            }
            else 
            {
                return BadRequest();
            }

            return RedirectToAction("ConvertidorVista", new { conversion = Conversion });
        }

        public IActionResult ConvertidorVista(string conversion) 
        {
            ViewBag.CONVERSION = conversion;
            return View();
        }

        public IActionResult Prestamos() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Prestamos(PrestamosVM pm/*double TasaInteres, double TipoPrestamo, double Monto, int Meses*/) 
        {
            double calculado = 0;
            double MontoNeto=0;
            double Intereses = 0;
            switch (pm.TipoPrestamo) 
            {
                case "1": Intereses = pm.TasaInteres / 100;
                    MontoNeto = pm.Monto + (pm.Monto * Intereses);
                    calculado = MontoNeto / pm.Meses;
                    calculado = Math.Round(calculado, 2);
                    break;

                case "2":
                    Intereses = pm.TasaInteres / 100;
                    MontoNeto = pm.Monto + (pm.Monto * Intereses);
                    calculado = MontoNeto / pm.Meses;
                    calculado = Math.Round(calculado, 2);
                    break;

                case "3":
                    Intereses = pm.TasaInteres / 100;
                    MontoNeto = pm.Monto + (pm.Monto * Intereses);
                    calculado = MontoNeto / pm.Meses;
                    calculado = Math.Round(calculado, 2);
                    break;
            }
            return RedirectToAction("PrestamosVista", new { calculado = calculado });
        }

       public IActionResult PrestamosVista(double calculado) 
        {
            ViewBag.CALCULADO = calculado;
            return View();
       } 
    }
}

MVC_Proyect1/Views/MVCapp/Convertidor.cshtml
@*Strong Typed*@
@model Application.ViewModel.ConversionVM


<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card">
            <div class="card-header bg-dark text-white">
                <h1>Conversor de monedas</h1>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="MVCapp" asp-action="Convertidor">

                    <div class="mb-3">
                        <label asp-for="Entrada" class="form-label">Ingrese el monto que desea convertir</label>
                        <input asp-for="Entrada" type="number" class="form-control" />
                    </div>


                    <div class="mb-3">
                        <label asp-for="Tipomoneda" class="form-label">Ingrese a la moneda que desea convertir</label>
                        <select asp-for="Tipomoneda" class="form-select">
                            <option>...</option>
                            <option value="1">Peso a Dolar</option>
                            <option value="2">Dolar a Peso</option>
                            <option value="3">Dolar a Euro</option>
                            <option value="4">Euro a Dolar</option>
                            <option value="5">Peso a Euro</option>
                            <option value="6">Euro a Peso</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-danger">Clear</button>

                </form>


            </div>
        </div>
    </div>
</div>

MVC_Proyect1/Views/MVCapp/ConvertidorVista.cshtml
@{

}
<div class="col-12">
    <div class="card">
        <div class="card card-header bg-dark text-white">Resultado de la conversion:</div>
        <div class="card card-body">
            <label for"tipomoneda1" class="col-form-label-lg">@ViewBag.CONVERSION</label>
            <a asp-action="Convertidor">Volver hacia atras...</a>
        </div>
    </div>
</div>

MVC_Proyect1/Views/MVCapp/Index.cshtml
@*Strong Typed*@
@model Application.ViewModel.Zodiaco


<div class="row-12">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-dark text-white">
                <h1>Signo Zodiacal</h1>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="MVCapp" asp-action="Index">

                    <div class="mb-3">
                        <label asp-for="Dia" class="form-label">Ingrese su día de nacimiento</label>
                        <input asp-for="Dia" type="number" class="form-control" />
                    </div>

                    <div class="mb-3">
                        <label asp-for="Mes" class="form-label">Ingrese su mes de nacimiento</label>
                        <select asp-for="Mes" class="form-select">
                            <option>...</option>
                            <option value="1">Enero</option>
                            <option value="2">Febrero</option>
                            <option value="3">Marzo</option>
                            <option value="4">Abril</option>
                            <option value="5">Mayo</option>
                            <option value="6">Junio</option>
                            <option value="7">Julio</option>
                            <option value="8">Agosto</option>
                            <option value="9">Septiembre</option>
                            <option value="10">Octubre</option>
                            <option value="11">Noviembre</option>
                            <option value="12">Diciembre</option>
                        </select>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-danger">Clear</button>
          
                </form>


            </div>
        </div>
    </div>
</div>

MVC_Proyect1/Views/MVCapp/Prestamos.cshtml
@*Strong Typed*@
@model Application.ViewModel.PrestamosVM
@{
    Application.ViewModel.PrestamosVM ol = new();
}


    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-dark text-white">
                <h1>Calculadora de Prestamos</h1>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="MVCapp" asp-action="Prestamos">

                    <div class="mb-3 row-cols-3">
                        <label asp-for="Monto" class="form-label">Monto: </label>
                        <input asp-for="Monto" type="number" class="form-control" />
                    </div>

                <div class="mb-3 row-cols-3">
                        <label asp-for="TipoPrestamo" class="form-label">Tipo de Prestamo</label>
                        <select asp-for="TipoPrestamo" class="form-select" id="tipo" onchange="prestamo()">
                            <option>...</option>
                            <option value="1">Personal</option>
                            <option value="2">Automovil</option>
                            <option value="3">Hipotecario</option>
                        </select>
                    </div>

                <div class="mb-3 row-cols-3">
                    <label>Meses:</label>
                    <select asp-for="Meses" class="form-control-sm">
                        <option>...</option>
                        @for (int meses = 12; meses <= 120; meses = meses + 6)
                        {
                            <option value=@meses>@meses Meses</option>
                        }
                    </select>
                    </div>

                    <div class="mb-3 row-cols-3">
                        <label asp-for="TasaInteres" class="form-label">Tasa Interes: </label>
                    <input asp-for="TasaInteres" readonly type="number" class="form-control" id="intereses" />
                    </div>

                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-danger">Clear</button>

                </form>
              

            </div>
        </div>
    </div>

<script>

    function prestamo() {
        const select = document.getElementById("tipo").value;
        if (select == 1) {
            const input = document.getElementById("intereses");
            input.value = 22;
        }
        else if (select == 2) {
            const input = document.getElementById("intereses");
            input.value = 12;
        }
        else if (select == 3) {
            const input = document.getElementById("intereses");
            input.value = 8;
        }
        else {
            const input = document.getElementById("intereses");
            input.value = 0;
        }
    }
</script>

MVC_Proyect1/Views/MVCapp/PrestamosVista.cshtml
<div class="col-12">
    <div class="card">
        <div class="card card-header bg-dark text-white">Calculo Finalizado: </div>
        <div class="card card-body">
            <label for"tipomoneda1" class="col-form-label-lg">@ViewBag.CALCULADO</label>
            <a asp-action="Prestamos">Volver hacia atras...</a>
        </div>
    </div>
</div>

MVC_Proyect1/Views/MVCapp/ZodiacoVista.cshtml
@model Application.ViewModel.Zodiaco
@{

}
<div class="col-12">
    <div class="card">
        <div class="card card-header bg-dark text-white">Su signo es: </div>
        <div class="card card-body">
            <label for"tipomoneda1" class="col-form-label-lg">@ViewBag.RESULTADO</label>
            <a asp-action="Index">Volver hacia atras...</a>
        </div>
    </div>
</div>

MVC_Proyect1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Proyect1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Proyect1.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="bg-dark">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="MVCapp" asp-action="Index">SellAppV1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MVCapp" asp-action="Index">Signo Zodiacal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MVCapp" asp-action="Convertidor">Conversor de Monedas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MVCapp" asp-action="Prestamos">Calculadora de Prestamos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-white">
            &copy; 2022 - Luis Junior Morla - 2020-10443 - <a asp-area="" asp-controller="MVCapp" asp-action="Index" class="text-opacity-75 text-white-50">Descubre tu Zodiaco</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>